version: '3.8'

services:
  watts_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: watts_api
    container_name: watts_api
    command: /watts_app/entrypoint.sh
    restart: unless-stopped
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=insecure_user
      - POSTGRES_PASSWORD=insecure_password
      - POSTGRES_DB=watts_api_db

volumes:
  postgres_data:
