# Generated by Django 4.1.3 on 2022-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WattConsume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_energy', models.FloatField()),
                ('meter_date', models.DateTimeField()),
                ('meter_id', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ('meter_date',),
            },
        ),
    ]
